name: build on FreeBSD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: apply the patch to libssh
      run: |
        git -C libssh fetch --all --tags --prune
        patch -d libssh -p1 < patch/$(git -C libssh describe).patch

    - name: Build in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: |
          pkg install -y git cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          build/mscp -h
