name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
    BUILD_TYPE: Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: patch to libssh
        run: patch -d libssh -p1 < patch/libssh-0.10.4.patch

      # TODO: just building docker does not require packages. fix CMakeLists
      - name: install build dependency
        run: sudo ./scripts/install-build-deps.sh

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Configure Cmake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Containers
        run: make -C ${{github.workspace}}/build docker-build-all

      - name: Test
        run: make -C ${{github.workspace}}/build docker-test-all

      - name: Retrieve packages from containers
        run: make -C ${{github.workspace}}/build docker-pkg-all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{github.workspace}}/build/mscp_${{env.VERSION}}-ubuntu-20.04-x86_64.deb
            ${{github.workspace}}/build/mscp_${{env.VERSION}}-ubuntu-22.04-x86_64.deb
            ${{github.workspace}}/build/mscp_${{env.VERSION}}-centos-8-x86_64.rpm
            ${{github.workspace}}/build/mscp_${{env.VERSION}}-rocky-8.6-x86_64.rpm

  source-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: patch to libssh
        run: patch -d libssh -p1 < patch/libssh-0.10.4.patch

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: archive
        run: |
          cd ..
          cp -r mscp mscp-${{env.VERSION}}
          tar zcvf mscp-${{env.VERSION}}.tar.gz --exclude-vcs mscp-${{env.VERSION}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{github.workspace}}/../mscp-${{env.VERSION}}.tar.gz
