name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
    BUILD_TYPE: Release

jobs:
  source-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: apply the patch to libssh
        run: |
          git -C libssh fetch --all --tags --prune
          patch -d libssh -p1 < patch/$(git -C libssh describe).patch

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: archive
        run: |
          cd ..
          cp -r mscp mscp-${{env.VERSION}}
          tar zcvf mscp-${{env.VERSION}}.tar.gz --exclude-vcs mscp-${{env.VERSION}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{github.workspace}}/../mscp-${{env.VERSION}}.tar.gz
