name: test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: patch to libssh
      run: patch -d libssh -p1 < patch/libssh-0.10.6.patch

    # TODO: just building docker does not require libssh. fix CMakeLists
    - name: install build dependency
      run: |
        sudo apt-get update
        sudo ./scripts/install-build-deps.sh

    - name: configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Containers
      run: make -C ${{github.workspace}}/build docker-build-all

    - name: Run Test
      run: make -C ${{github.workspace}}/build docker-test-all
