name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 22.04 container
      run: docker build --rm -t mscp-ubuntu:22.04 -f docker/ubuntu-22.04.Dockerfile .
    - name: Run test on ubuntu 22.04
      run: docker run --init --rm mscp-ubuntu:22.04 /mscp/scripts/test-in-container.sh

    - name: Build centos 8 container
      run: docker build --rm -t mscp-centos:8 -f docker/centos-8.Dockerfile .
    - name: Run test on centos 8
      run: docker run --init --rm mscp-centos:8 /mscp/scripts/test-in-container.sh
